name: "🐞 Bug Report"
description: Report a bug in the FastAPI app
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.

  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: "e.g. 3.11.6"
    validations:
      required: true

  - type: dropdown
    id: system
    attributes:
      label: Operating System
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: fastapi_version
    attributes:
      label: FastAPI Version
      placeholder: "e.g. 0.110.0"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened? What did you expect to happen?
      placeholder: "When I send a POST to /users, I get a 500 instead of a 201..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the issue
      placeholder: |
        1. Start the server
        2. Call `/users` endpoint with this payload...
        3. Observe the response
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Tracebacks
      description: Paste relevant logs or error messages
      render: shell
